"""Train a neural TwoRoom causal-tree path scorer.

First neural-generalization step:

  image(layout, goal, agent) + candidate physical path -> success score

The causal futures are still generated by a physics rollout library. The neural
part learns to score which candidate path is compatible with the visible
TwoRoom layout and goal, so held-out door positions/sizes can be tested without
hand-picking the route.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import time

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
import numpy as np
from mlx.utils import tree_flatten, tree_unflatten
from PIL import Image, ImageDraw, ImageFont

import record_tworoom_reflex_brain_video as viz
from train_tworoom_reflex_brain import sample_physics


IMG_SIZE = 32
PATH_POINTS = 24
SUCCESS_RADIUS = 12.0


def set_layout(door_center, door_half, goal_x, goal_y, start_x=44.0, start_y=160.0):
    viz.DOOR_CENTER = float(door_center)
    viz.DOOR_HALF = float(door_half)
    viz.START_STATE = np.array([
        float(start_x), float(start_y), 0.0, 0.0,
        float(goal_x), float(goal_y),
    ], dtype=np.float32)


def rollout_start_state(phys):
    state = viz.START_STATE.copy()
    hist = []
    for action in viz.scripted_probe_actions(seed=3):
        ns, _ = viz.step_state_stop_on_collision(state, action, phys)
        hist = viz.append_history(hist, state, action, ns)
        state = ns
    return state, hist


def render_layout_image(state, size=IMG_SIZE):
    img = np.zeros((size, size), dtype=np.float32)

    def to_ix(x):
        return int(np.clip(round(x / viz.WORLD * (size - 1)), 0, size - 1))

    x1 = to_ix(viz.WALL_X - viz.WALL_HALF)
    x2 = to_ix(viz.WALL_X + viz.WALL_HALF)
    y_top = to_ix(viz.DOOR_CENTER - viz.DOOR_HALF)
    y_bot = to_ix(viz.DOOR_CENTER + viz.DOOR_HALF)
    img[:, x1:x2 + 1] = 1.0
    img[y_top:y_bot + 1, x1:x2 + 1] = 0.0

    gx, gy = to_ix(state[4]), to_ix(state[5])
    sx, sy = to_ix(state[0]), to_ix(state[1])
    for yy in range(size):
        for xx in range(size):
            if (xx - gx) ** 2 + (yy - gy) ** 2 <= 3:
                img[yy, xx] = 0.65
            if (xx - sx) ** 2 + (yy - sy) ** 2 <= 2:
                img[yy, xx] = 0.35
    return img.reshape(-1)


def sampled_path_features(path, n_points=PATH_POINTS):
    if len(path) == 0:
        pts = np.zeros((n_points, 2), dtype=np.float32)
    else:
        idx = np.linspace(0, len(path) - 1, n_points)
        lo = np.floor(idx).astype(np.int32)
        hi = np.ceil(idx).astype(np.int32)
        frac = (idx - lo).astype(np.float32)[:, None]
        pts = path[lo] * (1.0 - frac) + path[hi] * frac
    return (pts / viz.WORLD - 0.5).astype(np.float32).reshape(-1)


def candidate_paths(state, phys, count=192, steps=150):
    """Generic action-program library.

    It does not use the true door center to pick a route. Branches either sweep
    possible pass-through heights, try goal-cone curves, or perform broad
    exploratory curves. The true geometry only affects the physics collision
    result.
    """
    paths = []
    goal = state[4:6]
    start = state[:2]
    goal_angle = float(np.arctan2(goal[1] - start[1], goal[0] - start[0]))
    pass_ys = np.linspace(28.0, viz.WORLD - 28.0, max(8, count // 2))

    for j in range(count):
        sim = state.copy()
        sim[2:4] = 0.0
        pts = [sim[:2].copy()]

        if j < len(pass_ys):
            primitive = "pass_y"
            pass_y = float(pass_ys[j])
        elif j < len(pass_ys) + count // 4:
            primitive = "goal_cone"
            k = j - len(pass_ys)
            frac = (k / max(1, count // 4 - 1)) - 0.5
            angle = goal_angle + 1.35 * frac
            curvature = [-0.018, 0.0, 0.018][k % 3]
        else:
            primitive = "broad_curve"
            k = j - len(pass_ys) - count // 4
            angle = 2.0 * np.pi * ((k * 37) % max(1, count)) / max(1, count)
            curvature = [-0.035, -0.018, 0.0, 0.018, 0.035][k % 5]

        for t in range(steps):
            if primitive == "pass_y":
                target = viz.choose_waypoint(sim, pass_y, goal)
                action = viz.steer_to(sim[:2], target, strength=1.0)
            else:
                action = viz.angle_action(angle + curvature * t)
            sim, collided = viz.step_state_stop_on_collision(sim, action, phys)
            pts.append(sim[:2].copy())
            if collided:
                break
        paths.append(np.asarray(pts, dtype=np.float32))
    return paths


def path_label(path, goal):
    d = float(np.min(np.linalg.norm(path - goal[None], axis=1)))
    return float(d <= SUCCESS_RADIUS), d


def truncate_path_at_goal(path, goal, radius=SUCCESS_RADIUS):
    d = np.linalg.norm(path - goal[None], axis=1)
    i = int(np.argmin(d))
    if float(d[i]) <= radius:
        return path[:i + 1].copy()
    return path.copy()


def random_layout(rng):
    door_half = float(rng.uniform(12.0, 32.0))
    door_center = float(rng.uniform(56.0 + door_half, 168.0 - door_half))
    goal_x = float(rng.uniform(172.0, 194.0))
    goal_y = float(rng.uniform(36.0, 188.0))
    start_y = float(rng.uniform(118.0, 178.0))
    return door_center, door_half, goal_x, goal_y, 44.0, start_y


def build_dataset(n_layouts, candidates, seed):
    rng = np.random.default_rng(seed)
    phys = sample_physics(np.random.default_rng(42))
    images, path_feats, labels, min_dists, layout_ids = [], [], [], [], []
    layouts = []

    for lid in range(n_layouts):
        layout = random_layout(rng)
        set_layout(*layout)
        state, _ = rollout_start_state(phys)
        img = render_layout_image(state)
        paths = candidate_paths(state, phys, candidates)
        goal = state[4:6]
        layouts.append({
            "door_center": layout[0],
            "door_half": layout[1],
            "goal_x": layout[2],
            "goal_y": layout[3],
            "start_x": layout[4],
            "start_y": layout[5],
        })
        for p in paths:
            y, d = path_label(p, goal)
            images.append(img)
            path_feats.append(sampled_path_features(p))
            labels.append(y)
            min_dists.append(d)
            layout_ids.append(lid)

    return {
        "image": np.asarray(images, dtype=np.float32),
        "path": np.asarray(path_feats, dtype=np.float32),
        "label": np.asarray(labels, dtype=np.float32),
        "min_dist": np.asarray(min_dists, dtype=np.float32),
        "layout_id": np.asarray(layout_ids, dtype=np.int32),
        "layouts": layouts,
        "n_layouts": n_layouts,
        "candidates": candidates,
    }


class CausalPathScorer(nn.Module):
    def __init__(self, input_dim, hidden=256):
        super().__init__()
        self.l1 = nn.Linear(input_dim, hidden)
        self.l2 = nn.Linear(hidden, hidden)
        self.l3 = nn.Linear(hidden, 128)
        self.out = nn.Linear(128, 1)

    def __call__(self, image, path):
        x = mx.concatenate([image, path], axis=-1)
        x = nn.relu(self.l1(x))
        x = nn.relu(self.l2(x))
        x = nn.relu(self.l3(x))
        return self.out(x).squeeze(-1)


def bce_logits(logits, labels, pos_weight=1.0):
    loss = mx.maximum(logits, 0) - logits * labels + mx.log1p(mx.exp(-mx.abs(logits)))
    weights = 1.0 + labels * (pos_weight - 1.0)
    return mx.mean(loss * weights)


def sigmoid_np(x):
    return 1.0 / (1.0 + np.exp(-x))


def eval_batch(model, data, idx):
    logits = model(mx.array(data["image"][idx]), mx.array(data["path"][idx]))
    mx.eval(logits)
    probs = sigmoid_np(np.array(logits, dtype=np.float32))
    y = data["label"][idx]
    acc = float(np.mean((probs >= 0.5) == (y >= 0.5)))
    return acc, float(np.mean(np.abs(probs - y)))


def eval_selection(model, data):
    selected_success = 0
    oracle_success = 0
    selected_dists = []
    top5_success = 0
    for lid in range(data["n_layouts"]):
        idx = np.where(data["layout_id"] == lid)[0]
        logits = model(mx.array(data["image"][idx]), mx.array(data["path"][idx]))
        mx.eval(logits)
        scores = np.array(logits, dtype=np.float32)
        order = np.argsort(-scores)
        labels = data["label"][idx]
        dists = data["min_dist"][idx]
        selected_success += int(labels[order[0]] >= 0.5)
        oracle_success += int(np.max(labels) >= 0.5)
        top5_success += int(np.max(labels[order[:5]]) >= 0.5)
        selected_dists.append(float(dists[order[0]]))
    n = max(1, data["n_layouts"])
    return {
        "selected_success": selected_success,
        "selected_success_rate": selected_success / n,
        "oracle_success": oracle_success,
        "oracle_success_rate": oracle_success / n,
        "top5_success": top5_success,
        "top5_success_rate": top5_success / n,
        "selected_dist_mean": float(np.mean(selected_dists)),
        "selected_dist_median": float(np.median(selected_dists)),
    }


def save_model(model, out_path):
    mx.savez(out_path, **dict(tree_flatten(model.parameters())))


def load_model(ckpt, hidden=256):
    input_dim = IMG_SIZE * IMG_SIZE + PATH_POINTS * 2
    model = CausalPathScorer(input_dim=input_dim, hidden=hidden)
    mx.eval(model.parameters())
    model.update(tree_unflatten(list(mx.load(ckpt).items())))
    mx.eval(model.parameters())
    return model


def train(args):
    os.makedirs(args.out_dir, exist_ok=True)
    cfg = vars(args) | {
        "img_size": IMG_SIZE,
        "path_points": PATH_POINTS,
        "success_radius": SUCCESS_RADIUS,
        "task": "image-conditioned causal path scoring",
    }
    with open(os.path.join(args.out_dir, "config.json"), "w") as f:
        json.dump(cfg, f, indent=2)

    print("[device]", mx.default_device())
    print("[data] generating neural causal scorer dataset...")
    t0 = time.time()
    train_data = build_dataset(args.train_layouts, args.candidates, args.seed)
    val_data = build_dataset(args.val_layouts, args.candidates, args.seed + 1000)
    print(f"[data] train={len(train_data['label'])} pos={train_data['label'].mean():.3f} "
          f"val={len(val_data['label'])} pos={val_data['label'].mean():.3f} "
          f"elapsed={time.time()-t0:.1f}s")
    np.savez_compressed(
        os.path.join(args.out_dir, "train_samples.npz"),
        image=train_data["image"], path=train_data["path"],
        label=train_data["label"], min_dist=train_data["min_dist"],
        layout_id=train_data["layout_id"],
    )
    np.savez_compressed(
        os.path.join(args.out_dir, "val_samples.npz"),
        image=val_data["image"], path=val_data["path"],
        label=val_data["label"], min_dist=val_data["min_dist"],
        layout_id=val_data["layout_id"],
    )
    with open(os.path.join(args.out_dir, "train_layouts.json"), "w") as f:
        json.dump(train_data["layouts"], f, indent=2)
    with open(os.path.join(args.out_dir, "val_layouts.json"), "w") as f:
        json.dump(val_data["layouts"], f, indent=2)

    input_dim = train_data["image"].shape[1] + train_data["path"].shape[1]
    model = CausalPathScorer(input_dim=input_dim, hidden=args.hidden)
    mx.eval(model.parameters())
    opt = optim.AdamW(learning_rate=args.lr, weight_decay=args.wd)
    pos_rate = float(train_data["label"].mean())
    pos_weight = min(8.0, max(1.0, (1.0 - pos_rate) / max(pos_rate, 1e-4)))

    def loss_fn(m, image, path, label):
        logits = m(image, path)
        return bce_logits(logits, label, pos_weight=pos_weight)

    grad_fn = nn.value_and_grad(model, loss_fn)
    rng = np.random.default_rng(args.seed)
    n_train = len(train_data["label"])
    n_val = len(val_data["label"])
    log = []
    t_train = time.time()

    for it in range(args.iters):
        idx = rng.integers(0, n_train, size=args.batch)
        image = mx.array(train_data["image"][idx])
        path = mx.array(train_data["path"][idx])
        label = mx.array(train_data["label"][idx])
        loss, grads = grad_fn(model, image, path, label)
        opt.update(model, grads)
        mx.eval(model.parameters(), opt.state, loss)

        if it % args.log_every == 0 or it == args.iters - 1:
            vidx = rng.choice(n_val, size=min(args.eval_batch, n_val), replace=False)
            acc, mae = eval_batch(model, val_data, vidx)
            sel = eval_selection(model, val_data)
            row = {
                "iter": it,
                "train_loss": float(loss.item()),
                "val_acc": acc,
                "val_prob_mae": mae,
                **sel,
            }
            log.append(row)
            print(f"[{it:5d}] loss={row['train_loss']:.4f} acc={acc:.3f} "
                  f"select={sel['selected_success']}/{val_data['n_layouts']} "
                  f"top5={sel['top5_success']}/{val_data['n_layouts']} "
                  f"oracle={sel['oracle_success']}/{val_data['n_layouts']} "
                  f"med_dist={sel['selected_dist_median']:.2f} "
                  f"elapsed={time.time()-t_train:.1f}s")

    ckpt = os.path.join(args.out_dir, "neural_causal_scorer.npz")
    save_model(model, ckpt)
    with open(os.path.join(args.out_dir, "metrics.json"), "w") as f:
        json.dump(log, f, indent=2)
    summary = {
        "ckpt": ckpt,
        "train_samples": int(n_train),
        "val_samples": int(n_val),
        "train_positive_rate": float(train_data["label"].mean()),
        "val_positive_rate": float(val_data["label"].mean()),
        "final": log[-1],
        "real_training": True,
    }
    with open(os.path.join(args.out_dir, "summary.json"), "w") as f:
        json.dump(summary, f, indent=2)
    print("[summary]", json.dumps(summary, indent=2))
    return ckpt


def draw_caption(draw, text):
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 18)
    except Exception:
        font = ImageFont.load_default()
    draw.rectangle([16, 14, viz.W - 16, 48], fill=(255, 255, 255), outline=(224, 228, 236))
    draw.text((28, 22), text, fill=(38, 43, 52), font=font)


def record_case(model, out_path, layout, candidates=240, frames=220):
    set_layout(*layout)
    phys = sample_physics(np.random.default_rng(42))
    state, hist = rollout_start_state(phys)
    paths = candidate_paths(state, phys, candidates)
    img_feat = render_layout_image(state)
    path_feat = np.asarray([sampled_path_features(p) for p in paths], dtype=np.float32)
    img_batch = np.repeat(img_feat[None], len(paths), axis=0)
    logits = model(mx.array(img_batch), mx.array(path_feat))
    mx.eval(logits)
    scores = np.array(logits, dtype=np.float32)
    order = np.argsort(-scores)
    selected = truncate_path_at_goal(paths[int(order[0])], state[4:6])
    top_paths = [paths[int(i)] for i in order[:12]]

    frame_dir = out_path + "_frames"
    if os.path.exists(frame_dir):
        shutil.rmtree(frame_dir)
    os.makedirs(frame_dir, exist_ok=True)

    exec_state = state.copy()
    real_trail = [exec_state[:2].copy()]
    collisions = []

    for frame in range(frames):
        if frame >= 78 and np.linalg.norm(exec_state[:2] - exec_state[4:6]) > SUCCESS_RADIUS:
            wp = viz.path_tracking_waypoint(selected, exec_state[:2], lookahead=8)
            action = viz.steer_to(exec_state[:2], wp, strength=1.0)
            ns, collided = viz.step_state_stop_on_collision(exec_state, action, phys)
            exec_state = ns
            real_trail.append(exec_state[:2].copy())
            if collided:
                collisions.append(exec_state[:2].copy())

        im = Image.new("RGB", (viz.W, viz.H), (249, 250, 252))
        draw = ImageDraw.Draw(im, "RGBA")
        viz.draw_base(draw)
        if frame < 36:
            caption = "neural scorer: candidate causal futures from image"
        elif frame < 78:
            caption = "neural scorer reinforces a candidate path"
        else:
            caption = "execution follows neural-selected causal chain"

        progress = 1.0 if frame >= 36 else frame / 35.0
        for p in paths:
            upto = int(2 + progress * (len(p) - 2))
            viz.draw_polyline(draw, p, color=(8, 145, 178, 42), width=1, upto=upto)
        if frame >= 36:
            conf = min(1.0, (frame - 36) / 42.0)
            for p in top_paths[1:]:
                viz.draw_polyline(draw, p, color=(37, 99, 235, 18), width=1)
            viz.draw_polyline(draw, selected, color=(37, 99, 235, int(36 + 100 * conf)),
                              width=max(2, int(2 + 3 * conf)))
            viz.draw_polyline(draw, selected, color=(220, 38, 38, int(35 + 115 * conf)),
                              width=max(2, int(2 + 3 * conf)))
        if len(real_trail) > 1:
            viz.draw_polyline(draw, np.asarray(real_trail), color=(153, 27, 27, 235), width=7)
        for cp in collisions:
            viz.draw_failure_marker(draw, cp)
        viz.draw_agent(draw, exec_state[:2])
        draw_caption(draw, caption)
        im.save(os.path.join(frame_dir, f"frame_{frame:05d}.png"))

    subprocess.run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-framerate", str(viz.FPS),
        "-i", os.path.join(frame_dir, "frame_%05d.png"),
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18",
        out_path,
    ], check=True)
    shutil.rmtree(frame_dir)


def make_gif(mp4_path):
    gif_path = os.path.splitext(mp4_path)[0] + ".gif"
    subprocess.run([
        "ffmpeg", "-y", "-loglevel", "error", "-i", mp4_path,
        "-vf", "fps=12,scale=520:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse",
        gif_path,
    ], check=True)
    return gif_path


def record(args):
    model = load_model(args.ckpt, hidden=args.hidden)
    os.makedirs(args.video_dir, exist_ok=True)
    cases = [
        ("neural_base", (98.0, 22.0, 184.0, 58.0, 44.0, 160.0)),
        ("neural_high_narrow", (72.0, 15.0, 184.0, 44.0, 44.0, 160.0)),
        ("neural_low_medium", (132.0, 18.0, 184.0, 156.0, 44.0, 160.0)),
        ("neural_wide_shifted", (88.0, 30.0, 188.0, 132.0, 44.0, 160.0)),
    ]
    outputs = []
    for name, layout in cases:
        mp4 = os.path.join(args.video_dir, f"{name}.mp4")
        record_case(model, mp4, layout, candidates=args.candidates, frames=args.frames)
        outputs.append(make_gif(mp4))
        print(outputs[-1])
    return outputs


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    tr = sub.add_parser("train")
    tr.add_argument("--train_layouts", type=int, default=220)
    tr.add_argument("--val_layouts", type=int, default=60)
    tr.add_argument("--candidates", type=int, default=192)
    tr.add_argument("--iters", type=int, default=1600)
    tr.add_argument("--batch", type=int, default=512)
    tr.add_argument("--eval_batch", type=int, default=4096)
    tr.add_argument("--hidden", type=int, default=256)
    tr.add_argument("--lr", type=float, default=5e-4)
    tr.add_argument("--wd", type=float, default=1e-5)
    tr.add_argument("--seed", type=int, default=7)
    tr.add_argument("--log_every", type=int, default=200)
    tr.add_argument("--out_dir", default="meadow/tworoom_neural_causal_scorer")

    rec = sub.add_parser("record")
    rec.add_argument("--ckpt", default="meadow/tworoom_neural_causal_scorer/neural_causal_scorer.npz")
    rec.add_argument("--hidden", type=int, default=256)
    rec.add_argument("--candidates", type=int, default=240)
    rec.add_argument("--frames", type=int, default=220)
    rec.add_argument("--video_dir", default="meadow/tworoom_neural_causal_scorer/videos")

    args = ap.parse_args()
    if args.cmd == "train":
        train(args)
    else:
        record(args)


if __name__ == "__main__":
    main()
