"""Train a neural Cube orientation causal-path scorer.

Fourth Meadow WM task prototype:

  image(current cube, target cube) + candidate angular future -> success score

This mirrors the TwoRoom neural causal scorer, but the physical state is cube
orientation instead of 2D navigation. The candidate futures are generated by a
small angular-dynamics library; the neural part learns to choose which future
rotates the cube close to the target orientation on held-out start/goal pairs.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import time

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
import numpy as np
from mlx.utils import tree_flatten, tree_unflatten
from PIL import Image, ImageDraw, ImageFont


IMG_SIZE = 32
PATH_POINTS = 20
SUCCESS_ANGLE = 0.20
DT = 0.25
WORLD_W = 760
WORLD_H = 520
FPS = 24


def wrap_angle(x):
    return (x + np.pi) % (2.0 * np.pi) - np.pi


def angle_delta(a, b):
    return wrap_angle(b - a)


def angle_dist(a, b):
    d = angle_delta(a, b)
    return float(np.sqrt(np.mean(d * d)))


def rot_matrix(angles):
    rx, ry, rz = angles
    cx, sx = np.cos(rx), np.sin(rx)
    cy, sy = np.cos(ry), np.sin(ry)
    cz, sz = np.cos(rz), np.sin(rz)
    rxm = np.array([[1, 0, 0], [0, cx, -sx], [0, sx, cx]], dtype=np.float32)
    rym = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]], dtype=np.float32)
    rzm = np.array([[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]], dtype=np.float32)
    return rzm @ rym @ rxm


VERTS = np.array(
    [
        [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
        [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
    ],
    dtype=np.float32,
)
EDGES = [
    (0, 1), (1, 2), (2, 3), (3, 0),
    (4, 5), (5, 6), (6, 7), (7, 4),
    (0, 4), (1, 5), (2, 6), (3, 7),
]
AXES = np.array([[1.35, 0, 0], [0, 1.35, 0], [0, 0, 1.35]], dtype=np.float32)


def project_points(points, angles, center, scale):
    pts = points @ rot_matrix(angles).T
    # Fixed oblique camera gives visible 3D structure while staying lightweight.
    cam = np.array([[1.0, 0.0, 0.35], [0.0, -0.95, -0.25]], dtype=np.float32)
    p2 = pts @ cam.T
    p2[:, 0] = center[0] + p2[:, 0] * scale
    p2[:, 1] = center[1] + p2[:, 1] * scale
    return p2


def draw_cube(draw, angles, center, scale, color, width=3, alpha=255):
    pts = project_points(VERTS, angles, center, scale)
    rgba = (*color, alpha)
    for a, b in EDGES:
        draw.line([tuple(pts[a]), tuple(pts[b])], fill=rgba, width=width)
    origin = project_points(np.zeros((1, 3), dtype=np.float32), angles, center, scale)[0]
    axis_pts = project_points(AXES, angles, center, scale)
    axis_cols = [(220, 38, 38), (22, 163, 74), (37, 99, 235)]
    for pt, col in zip(axis_pts, axis_cols):
        draw.line([tuple(origin), tuple(pt)], fill=(*col, alpha), width=max(1, width - 1))
        draw.ellipse([pt[0] - 3, pt[1] - 3, pt[0] + 3, pt[1] + 3], fill=(*col, alpha))


def render_layout_image(start, target, size=IMG_SIZE):
    im = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(im, "L")

    def small_cube(angles, center, scale, shade, width):
        pts = project_points(VERTS, angles, center, scale)
        for a, b in EDGES:
            draw.line([tuple(pts[a]), tuple(pts[b])], fill=shade, width=width)
        origin = project_points(np.zeros((1, 3), dtype=np.float32), angles, center, scale)[0]
        axis_pts = project_points(AXES, angles, center, scale)
        for pt in axis_pts:
            draw.line([tuple(origin), tuple(pt)], fill=shade, width=width)

    small_cube(target, (23, 16), 5.2, 100, 1)
    small_cube(start, (9, 16), 5.7, 220, 1)
    draw.line([(15, 16), (17, 16)], fill=160, width=1)
    return np.asarray(im, dtype=np.float32).reshape(-1) / 255.0


def step_orientation(angles, vel, action, damping=0.82):
    action = np.clip(action, -1.0, 1.0).astype(np.float32)
    vel = damping * vel + 0.22 * action
    angles = wrap_angle(angles + vel * DT)
    return angles.astype(np.float32), vel.astype(np.float32)


def candidate_paths(start, target, count=192, steps=90):
    paths = []
    base_delta = angle_delta(start, target)
    base_norm = np.linalg.norm(base_delta) + 1e-6
    base_axis = base_delta / base_norm

    for j in range(count):
        angles = start.astype(np.float32).copy()
        vel = np.zeros(3, dtype=np.float32)
        pts = [angles.copy()]

        if j < count // 2:
            primitive = "target_pd"
            gain = np.linspace(0.45, 1.75, max(1, count // 2))[j]
            wobble = [-0.18, -0.08, 0.0, 0.08, 0.18][j % 5]
            phase = 0.37 * j
        elif j < 3 * count // 4:
            primitive = "single_axis"
            k = j - count // 2
            axis_id = k % 3
            sign = -1.0 if (k // 3) % 2 else 1.0
            strength = 0.35 + 0.015 * (k % 24)
        else:
            primitive = "broad_axis"
            k = j - 3 * count // 4
            theta = 2.0 * np.pi * ((k * 17) % max(1, count)) / max(1, count)
            phi = -0.9 + 1.8 * ((k * 29) % max(1, count)) / max(1, count)
            axis = np.array([
                np.cos(theta) * np.cos(phi),
                np.sin(theta) * np.cos(phi),
                np.sin(phi),
            ], dtype=np.float32)
            strength = 0.45 + 0.25 * ((k % 7) / 6.0)

        for t in range(steps):
            if primitive == "target_pd":
                err = angle_delta(angles, target)
                spin = np.array([
                    np.sin(0.12 * t + phase),
                    np.sin(0.09 * t + phase + 1.7),
                    np.sin(0.07 * t + phase + 3.1),
                ], dtype=np.float32)
                action = gain * err + wobble * spin + 0.10 * base_axis
            elif primitive == "single_axis":
                action = np.zeros(3, dtype=np.float32)
                action[axis_id] = sign * strength
            else:
                action = axis * strength
            angles, vel = step_orientation(angles, vel, action)
            pts.append(angles.copy())
            if angle_dist(angles, target) <= SUCCESS_ANGLE:
                break
        paths.append(np.asarray(pts, dtype=np.float32))
    return paths


def sampled_path_features(path, n_points=PATH_POINTS):
    idx = np.linspace(0, len(path) - 1, n_points)
    lo = np.floor(idx).astype(np.int32)
    hi = np.ceil(idx).astype(np.int32)
    frac = (idx - lo).astype(np.float32)[:, None]
    pts = path[lo] * (1.0 - frac) + path[hi] * frac
    return (pts / np.pi).astype(np.float32).reshape(-1)


def path_label(path, target):
    dists = np.asarray([angle_dist(p, target) for p in path], dtype=np.float32)
    d = float(np.min(dists))
    return float(d <= SUCCESS_ANGLE), d


def truncate_path_at_target(path, target, radius=SUCCESS_ANGLE):
    dists = np.asarray([angle_dist(p, target) for p in path], dtype=np.float32)
    i = int(np.argmin(dists))
    if float(dists[i]) <= radius:
        return path[:i + 1].copy()
    return path.copy()


def random_case(rng):
    start = rng.uniform(-np.pi, np.pi, size=3).astype(np.float32)
    target = rng.uniform(-np.pi, np.pi, size=3).astype(np.float32)
    # Keep some cases near enough that angular dynamics can solve quickly, but
    # still randomize all three axes.
    if rng.random() < 0.55:
        target = wrap_angle(start + rng.uniform(-1.8, 1.8, size=3)).astype(np.float32)
    return start, target


def build_dataset(n_cases, candidates, seed):
    rng = np.random.default_rng(seed)
    images, path_feats, labels, min_dists, case_ids = [], [], [], [], []
    cases = []
    for cid in range(n_cases):
        start, target = random_case(rng)
        img = render_layout_image(start, target)
        paths = candidate_paths(start, target, candidates)
        cases.append({"start": start.tolist(), "target": target.tolist()})
        for p in paths:
            y, d = path_label(p, target)
            images.append(img)
            path_feats.append(sampled_path_features(p))
            labels.append(y)
            min_dists.append(d)
            case_ids.append(cid)
    return {
        "image": np.asarray(images, dtype=np.float32),
        "path": np.asarray(path_feats, dtype=np.float32),
        "label": np.asarray(labels, dtype=np.float32),
        "min_dist": np.asarray(min_dists, dtype=np.float32),
        "case_id": np.asarray(case_ids, dtype=np.int32),
        "cases": cases,
        "n_cases": n_cases,
        "candidates": candidates,
    }


class CausalPathScorer(nn.Module):
    def __init__(self, input_dim, hidden=256):
        super().__init__()
        self.l1 = nn.Linear(input_dim, hidden)
        self.l2 = nn.Linear(hidden, hidden)
        self.l3 = nn.Linear(hidden, 128)
        self.out = nn.Linear(128, 1)

    def __call__(self, image, path):
        x = mx.concatenate([image, path], axis=-1)
        x = nn.relu(self.l1(x))
        x = nn.relu(self.l2(x))
        x = nn.relu(self.l3(x))
        return self.out(x).squeeze(-1)


def bce_logits(logits, labels, pos_weight=1.0):
    loss = mx.maximum(logits, 0) - logits * labels + mx.log1p(mx.exp(-mx.abs(logits)))
    weights = 1.0 + labels * (pos_weight - 1.0)
    return mx.mean(loss * weights)


def sigmoid_np(x):
    return 1.0 / (1.0 + np.exp(-x))


def eval_batch(model, data, idx):
    logits = model(mx.array(data["image"][idx]), mx.array(data["path"][idx]))
    mx.eval(logits)
    probs = sigmoid_np(np.array(logits, dtype=np.float32))
    y = data["label"][idx]
    acc = float(np.mean((probs >= 0.5) == (y >= 0.5)))
    return acc, float(np.mean(np.abs(probs - y)))


def eval_selection(model, data):
    selected_success = 0
    oracle_success = 0
    top5_success = 0
    selected_dists = []
    for cid in range(data["n_cases"]):
        idx = np.where(data["case_id"] == cid)[0]
        logits = model(mx.array(data["image"][idx]), mx.array(data["path"][idx]))
        mx.eval(logits)
        scores = np.array(logits, dtype=np.float32)
        order = np.argsort(-scores)
        labels = data["label"][idx]
        dists = data["min_dist"][idx]
        selected_success += int(labels[order[0]] >= 0.5)
        oracle_success += int(np.max(labels) >= 0.5)
        top5_success += int(np.max(labels[order[:5]]) >= 0.5)
        selected_dists.append(float(dists[order[0]]))
    n = max(1, data["n_cases"])
    return {
        "selected_success": selected_success,
        "selected_success_rate": selected_success / n,
        "oracle_success": oracle_success,
        "oracle_success_rate": oracle_success / n,
        "top5_success": top5_success,
        "top5_success_rate": top5_success / n,
        "selected_dist_mean": float(np.mean(selected_dists)),
        "selected_dist_median": float(np.median(selected_dists)),
    }


def save_model(model, out_path):
    mx.savez(out_path, **dict(tree_flatten(model.parameters())))


def load_model(ckpt, hidden=256):
    input_dim = IMG_SIZE * IMG_SIZE + PATH_POINTS * 3
    model = CausalPathScorer(input_dim=input_dim, hidden=hidden)
    mx.eval(model.parameters())
    model.update(tree_unflatten(list(mx.load(ckpt).items())))
    mx.eval(model.parameters())
    return model


def train(args):
    os.makedirs(args.out_dir, exist_ok=True)
    cfg = vars(args) | {
        "img_size": IMG_SIZE,
        "path_points": PATH_POINTS,
        "success_angle": SUCCESS_ANGLE,
        "task": "cube image-conditioned causal orientation scoring",
    }
    with open(os.path.join(args.out_dir, "config.json"), "w") as f:
        json.dump(cfg, f, indent=2)

    print("[device]", mx.default_device())
    print("[data] generating cube neural causal scorer dataset...")
    t0 = time.time()
    train_data = build_dataset(args.train_cases, args.candidates, args.seed)
    val_data = build_dataset(args.val_cases, args.candidates, args.seed + 1000)
    print(f"[data] train={len(train_data['label'])} pos={train_data['label'].mean():.3f} "
          f"val={len(val_data['label'])} pos={val_data['label'].mean():.3f} "
          f"elapsed={time.time()-t0:.1f}s")

    np.savez_compressed(
        os.path.join(args.out_dir, "train_samples.npz"),
        image=train_data["image"], path=train_data["path"],
        label=train_data["label"], min_dist=train_data["min_dist"],
        case_id=train_data["case_id"],
    )
    np.savez_compressed(
        os.path.join(args.out_dir, "val_samples.npz"),
        image=val_data["image"], path=val_data["path"],
        label=val_data["label"], min_dist=val_data["min_dist"],
        case_id=val_data["case_id"],
    )
    with open(os.path.join(args.out_dir, "train_cases.json"), "w") as f:
        json.dump(train_data["cases"], f, indent=2)
    with open(os.path.join(args.out_dir, "val_cases.json"), "w") as f:
        json.dump(val_data["cases"], f, indent=2)

    input_dim = train_data["image"].shape[1] + train_data["path"].shape[1]
    model = CausalPathScorer(input_dim=input_dim, hidden=args.hidden)
    mx.eval(model.parameters())
    opt = optim.AdamW(learning_rate=args.lr, weight_decay=args.wd)
    pos_rate = float(train_data["label"].mean())
    pos_weight = min(8.0, max(1.0, (1.0 - pos_rate) / max(pos_rate, 1e-4)))

    def loss_fn(m, image, path, label):
        return bce_logits(m(image, path), label, pos_weight=pos_weight)

    grad_fn = nn.value_and_grad(model, loss_fn)
    rng = np.random.default_rng(args.seed)
    n_train = len(train_data["label"])
    n_val = len(val_data["label"])
    log = []
    t_train = time.time()

    for it in range(args.iters):
        idx = rng.integers(0, n_train, size=args.batch)
        loss, grads = grad_fn(
            model,
            mx.array(train_data["image"][idx]),
            mx.array(train_data["path"][idx]),
            mx.array(train_data["label"][idx]),
        )
        opt.update(model, grads)
        mx.eval(model.parameters(), opt.state, loss)

        if it % args.log_every == 0 or it == args.iters - 1:
            vidx = rng.choice(n_val, size=min(args.eval_batch, n_val), replace=False)
            acc, mae = eval_batch(model, val_data, vidx)
            sel = eval_selection(model, val_data)
            row = {
                "iter": it,
                "train_loss": float(loss.item()),
                "val_acc": acc,
                "val_prob_mae": mae,
                **sel,
            }
            log.append(row)
            print(f"[{it:5d}] loss={row['train_loss']:.4f} acc={acc:.3f} "
                  f"select={sel['selected_success']}/{val_data['n_cases']} "
                  f"top5={sel['top5_success']}/{val_data['n_cases']} "
                  f"oracle={sel['oracle_success']}/{val_data['n_cases']} "
                  f"med_dist={sel['selected_dist_median']:.3f} "
                  f"elapsed={time.time()-t_train:.1f}s")

    ckpt = os.path.join(args.out_dir, "neural_causal_scorer.npz")
    save_model(model, ckpt)
    with open(os.path.join(args.out_dir, "metrics.json"), "w") as f:
        json.dump(log, f, indent=2)
    summary = {
        "ckpt": ckpt,
        "train_samples": int(n_train),
        "val_samples": int(n_val),
        "train_positive_rate": float(train_data["label"].mean()),
        "val_positive_rate": float(val_data["label"].mean()),
        "final": log[-1],
        "real_training": True,
    }
    with open(os.path.join(args.out_dir, "summary.json"), "w") as f:
        json.dump(summary, f, indent=2)
    print("[summary]", json.dumps(summary, indent=2))
    return ckpt


def font(size=18):
    try:
        return ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", size)
    except Exception:
        return ImageFont.load_default()


def draw_caption(draw, text):
    draw.rectangle([18, 14, WORLD_W - 18, 52], fill=(255, 255, 255, 238), outline=(224, 228, 236))
    draw.text((30, 24), text, fill=(38, 43, 52), font=font(18))


def draw_phase_path(draw, path, target, box, color, width=2, alpha=90, upto=None):
    x0, y0, x1, y1 = box
    if upto is None:
        upto = len(path)
    pts = []
    for p in path[:max(2, upto)]:
        x = x0 + (p[2] / np.pi + 1.0) * 0.5 * (x1 - x0)
        y = y1 - (p[1] / np.pi + 1.0) * 0.5 * (y1 - y0)
        pts.append((float(x), float(y)))
    if len(pts) > 1:
        draw.line(pts, fill=(*color, alpha), width=width)
    tx = x0 + (target[2] / np.pi + 1.0) * 0.5 * (x1 - x0)
    ty = y1 - (target[1] / np.pi + 1.0) * 0.5 * (y1 - y0)
    draw.ellipse([tx - 7, ty - 7, tx + 7, ty + 7], outline=(22, 101, 52, 230), width=3)


def record_case(model, out_path, start, target, candidates=240, frames=190):
    paths = candidate_paths(start, target, candidates)
    img_feat = render_layout_image(start, target)
    path_feat = np.asarray([sampled_path_features(p) for p in paths], dtype=np.float32)
    img_batch = np.repeat(img_feat[None], len(paths), axis=0)
    logits = model(mx.array(img_batch), mx.array(path_feat))
    mx.eval(logits)
    scores = np.array(logits, dtype=np.float32)
    order = np.argsort(-scores)
    selected = truncate_path_at_target(paths[int(order[0])], target)
    top_paths = [paths[int(i)] for i in order[:12]]

    frame_dir = out_path + "_frames"
    if os.path.exists(frame_dir):
        shutil.rmtree(frame_dir)
    os.makedirs(frame_dir, exist_ok=True)

    exec_i = 0
    exec_angles = start.copy()
    phase_box = (430, 110, 720, 430)

    for frame in range(frames):
        if frame >= 72 and exec_i < len(selected) - 1 and angle_dist(exec_angles, target) > SUCCESS_ANGLE:
            exec_i += 1
            exec_angles = selected[exec_i].copy()

        im = Image.new("RGB", (WORLD_W, WORLD_H), (249, 250, 252))
        draw = ImageDraw.Draw(im, "RGBA")
        draw.rectangle([390, 78, 738, 456], fill=(255, 255, 255, 245), outline=(219, 225, 235), width=2)
        draw.text((430, 82), "candidate futures in yaw/pitch space", fill=(71, 85, 105), font=font(15))
        draw.line([(phase_box[0], (phase_box[1] + phase_box[3]) / 2),
                   (phase_box[2], (phase_box[1] + phase_box[3]) / 2)], fill=(203, 213, 225, 180), width=1)
        draw.line([((phase_box[0] + phase_box[2]) / 2, phase_box[1]),
                   ((phase_box[0] + phase_box[2]) / 2, phase_box[3])], fill=(203, 213, 225, 180), width=1)

        if frame < 34:
            caption = "cube neural scorer: candidate angular futures from image"
        elif frame < 72:
            caption = "neural scorer reinforces a successful orientation chain"
        else:
            caption = "execution follows neural-selected rotation and stops near target"

        progress = 1.0 if frame >= 34 else frame / 33.0
        for p in paths:
            upto = int(2 + progress * (len(p) - 2))
            draw_phase_path(draw, p, target, phase_box, (8, 145, 178), width=1, alpha=34, upto=upto)
        if frame >= 34:
            conf = min(1.0, (frame - 34) / 38.0)
            for p in top_paths[1:]:
                draw_phase_path(draw, p, target, phase_box, (37, 99, 235), width=1, alpha=28)
            draw_phase_path(draw, selected, target, phase_box, (37, 99, 235), width=max(2, int(2 + 3 * conf)), alpha=int(70 + 120 * conf))
            draw_phase_path(draw, selected, target, phase_box, (220, 38, 38), width=max(2, int(2 + 2 * conf)), alpha=int(70 + 120 * conf))

        draw.text((62, 88), "current", fill=(71, 85, 105), font=font(16))
        draw.text((232, 88), "target", fill=(71, 85, 105), font=font(16))
        draw_cube(draw, target, (262, 265), 58, (22, 101, 52), width=2, alpha=90)
        draw_cube(draw, exec_angles, (140, 265), 70, (220, 38, 38), width=5, alpha=235)

        dist = angle_dist(exec_angles, target)
        draw.rectangle([58, 424, 350, 454], fill=(255, 255, 255, 235), outline=(226, 232, 240))
        draw.text((70, 431), f"orientation error: {dist:.3f} rad", fill=(38, 43, 52), font=font(17))
        if dist <= SUCCESS_ANGLE:
            draw.ellipse([318, 428, 336, 446], fill=(22, 163, 74, 230))

        draw_caption(draw, caption)
        im.save(os.path.join(frame_dir, f"frame_{frame:05d}.png"))

    subprocess.run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-framerate", str(FPS),
        "-i", os.path.join(frame_dir, "frame_%05d.png"),
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18",
        out_path,
    ], check=True)
    shutil.rmtree(frame_dir)


def make_gif(mp4_path):
    gif_path = os.path.splitext(mp4_path)[0] + ".gif"
    subprocess.run([
        "ffmpeg", "-y", "-loglevel", "error", "-i", mp4_path,
        "-vf", "fps=12,scale=560:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse",
        gif_path,
    ], check=True)
    return gif_path


def record(args):
    model = load_model(args.ckpt, hidden=args.hidden)
    os.makedirs(args.video_dir, exist_ok=True)
    cases = [
        ("cube_base", np.array([-1.4, 0.55, -2.2], dtype=np.float32), np.array([1.1, -0.7, 0.95], dtype=np.float32)),
        ("cube_roll_pitch", np.array([2.5, -1.1, 0.3], dtype=np.float32), np.array([-0.6, 1.2, -0.2], dtype=np.float32)),
        ("cube_yaw_flip", np.array([0.1, 0.4, -2.8], dtype=np.float32), np.array([0.2, -0.3, 2.6], dtype=np.float32)),
        ("cube_compound", np.array([-2.2, 1.35, 1.7], dtype=np.float32), np.array([1.9, -1.15, -1.4], dtype=np.float32)),
    ]
    outputs = []
    for name, start, target in cases:
        mp4 = os.path.join(args.video_dir, f"{name}.mp4")
        record_case(model, mp4, start, target, candidates=args.candidates, frames=args.frames)
        outputs.append(make_gif(mp4))
        print(outputs[-1])
    return outputs


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    tr = sub.add_parser("train")
    tr.add_argument("--train_cases", type=int, default=260)
    tr.add_argument("--val_cases", type=int, default=80)
    tr.add_argument("--candidates", type=int, default=192)
    tr.add_argument("--iters", type=int, default=1600)
    tr.add_argument("--batch", type=int, default=512)
    tr.add_argument("--eval_batch", type=int, default=4096)
    tr.add_argument("--hidden", type=int, default=256)
    tr.add_argument("--lr", type=float, default=5e-4)
    tr.add_argument("--wd", type=float, default=1e-5)
    tr.add_argument("--seed", type=int, default=11)
    tr.add_argument("--log_every", type=int, default=200)
    tr.add_argument("--out_dir", default="meadow/cube_neural_causal_scorer")

    rec = sub.add_parser("record")
    rec.add_argument("--ckpt", default="meadow/cube_neural_causal_scorer/neural_causal_scorer.npz")
    rec.add_argument("--hidden", type=int, default=256)
    rec.add_argument("--candidates", type=int, default=240)
    rec.add_argument("--frames", type=int, default=190)
    rec.add_argument("--video_dir", default="meadow/cube_neural_causal_scorer/videos")

    args = ap.parse_args()
    if args.cmd == "train":
        train(args)
    else:
        record(args)


if __name__ == "__main__":
    main()
